sudo: false
language: java
jdk:
  - openjdk8

script:
  - mvn clean package -Dmaven.test.skip=true

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file: "target/p3c-pmd-2.1.1.jar"
  on:
    tags: true
