sudo: false
language: java
jdk:
  - openjdk8

script:
  - mvn clean package -Dmaven.test.skip=true

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: releases
  tag_name: p3c-pmd-2.1.0
  name: p3c-pmd-2.1.0
  api_key: $GH_TOKEN
  skip_cleanup: true
  file_glob: true
  file:
    - target/p3c-pmd-2.1.1-javadoc.jar
  on:
    tags: true
