sudo: false
language: java
jdk:
  - openjdk8

script:
  - mvn clean package -Dmaven.test.skip=true

cache:
  directories:
    - '$HOME/.m2/repository'

deploy:
  provider: releases
  github-token: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
